# Generated by Django 2.0.6 on 2019-05-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=40)),
                ('r_adress', models.CharField(max_length=40)),
                ('e_number', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 't_adress',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=40)),
                ('pb_house', models.CharField(max_length=80)),
                ('pb_time', models.DateTimeField(auto_now_add=True)),
                ('pb_number', models.CharField(max_length=10)),
                ('ibsn', models.CharField(max_length=80)),
                ('b_number', models.CharField(max_length=20)),
                ('page_number', models.CharField(max_length=20)),
                ('formats', models.CharField(max_length=20)),
                ('page', models.CharField(max_length=40)),
                ('pack', models.CharField(max_length=40)),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(upload_to='pic')),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('all_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statue', models.CharField(max_length=20)),
                ('adress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Adress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_number', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Order')),
            ],
            options={
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('b_number', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_sort',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('statue', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Sort'),
        ),
        migrations.AddField(
            model_name='adress',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.User'),
        ),
    ]
