# Generated by Django 2.0.6 on 2019-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='onlinetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
