# Generated by Django 2.0.6 on 2019-05-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_book_onlinetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
