# Generated by Django 2.0.6 on 2019-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_book_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
