# Generated by Django 2.0.6 on 2019-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_auto_20190523_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('pid', models.CharField(max_length=20)),
                ('cityname', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
