# Generated by Django 2.0.6 on 2019-05-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0010_auto_20190526_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm_string',
            name='user',
        ),
    ]
