# Generated by Django 2.0.6 on 2019-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0011_remove_confirm_string_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_code',
            },
        ),
    ]
