# Generated by Django 2.0.6 on 2019-05-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0012_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='t_city',
        ),
    ]
