# Generated by Django 2.0.6 on 2019-05-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0013_auto_20190526_1711'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
